// This file is generated by the discover-tests script

#include "rs-core/unit-test.hpp"

using namespace RS::UnitTest;

void test_rs_core_enum();
void test_rs_core_enum_bitmask();
void test_rs_core_format_concepts();
void test_rs_core_format_automation();
void test_rs_core_global_bitmask_functions();
void test_rs_core_global_character_functions();
void test_rs_core_global_range_functions();
void test_rs_core_hash_kernighan();
void test_rs_core_hash_mix();
void test_rs_core_hash_standard();
void test_rs_core_version();

int main(int argc, char** argv) {

    main_args = std::vector<std::string>(argv + 1, argv + argc);
    std::println("");
    std::println("{}Running unit tests{}", xhead, xreset);
    std::println("{}{}{}", xrule, rule, xreset);

    call_me_maybe(test_rs_core_enum, "test_rs_core_enum");
    call_me_maybe(test_rs_core_enum_bitmask, "test_rs_core_enum_bitmask");
    call_me_maybe(test_rs_core_format_concepts, "test_rs_core_format_concepts");
    call_me_maybe(test_rs_core_format_automation, "test_rs_core_format_automation");
    call_me_maybe(test_rs_core_global_bitmask_functions, "test_rs_core_global_bitmask_functions");
    call_me_maybe(test_rs_core_global_character_functions, "test_rs_core_global_character_functions");
    call_me_maybe(test_rs_core_global_range_functions, "test_rs_core_global_range_functions");
    call_me_maybe(test_rs_core_hash_kernighan, "test_rs_core_hash_kernighan");
    call_me_maybe(test_rs_core_hash_mix, "test_rs_core_hash_mix");
    call_me_maybe(test_rs_core_hash_standard, "test_rs_core_hash_standard");
    call_me_maybe(test_rs_core_version, "test_rs_core_version");

    std::println("{}{}{}", xrule, rule, xreset);

    if (failures == 0) {
        std::println("{}OK - all tests passed{}", xpass, xreset);
    } else {
        std::println("{}*** Test failures: {}{}", xfail, failures, xreset);
    }

    std::println("");

    return failures;

}
